#include "backend/native_state.h"

#include "ir/dolir.h"

void emit_native_state_commit(FILE* out) {
    fprintf(out,
            "\nenum {\n"
            " MG_STATE_GPR0=%uu, MG_STATE_FPR0=%uu, MG_STATE_PS1_0=%uu,\n"
            " MG_STATE_LR=%uu, MG_STATE_CTR=%uu, MG_STATE_CR=%uu,\n"
            " MG_STATE_CR0=%uu, MG_STATE_XER=%uu, MG_STATE_XER_CA=%uu,\n"
            " MG_STATE_XER_OV=%uu, MG_STATE_XER_SO=%uu, MG_STATE_FPSCR=%uu,\n"
            " MG_STATE_MSR=%uu, MG_STATE_SRR0=%uu, MG_STATE_SRR1=%uu,\n"
            " MG_STATE_DAR=%uu, MG_STATE_DSISR=%uu, MG_STATE_EAR=%uu,\n"
            " MG_STATE_HID2=%uu, MG_STATE_SR0=%uu, MG_STATE_GQR0=%uu,\n"
            " MG_STATE_EXCEPTION=%uu, MG_STATE_RESERVE_ADDR=%uu,\n"
            " MG_STATE_RESERVE_VALID=%uu\n"
            "};\n",
            DOLIR_STATE_GPR0, DOLIR_STATE_FPR0, DOLIR_STATE_PS1_0,
            DOLIR_STATE_LR, DOLIR_STATE_CTR, DOLIR_STATE_CR,
            DOLIR_STATE_CR0, DOLIR_STATE_XER, DOLIR_STATE_XER_CA,
            DOLIR_STATE_XER_OV, DOLIR_STATE_XER_SO, DOLIR_STATE_FPSCR,
            DOLIR_STATE_MSR, DOLIR_STATE_SRR0, DOLIR_STATE_SRR1,
            DOLIR_STATE_DAR, DOLIR_STATE_DSISR, DOLIR_STATE_EAR,
            DOLIR_STATE_HID2, DOLIR_STATE_SR0, DOLIR_STATE_GQR0,
            DOLIR_STATE_EXCEPTION, DOLIR_STATE_RESERVE_ADDR,
            DOLIR_STATE_RESERVE_VALID);
    fputs(
        "enum {\n"
        " MG_SPR_LR=8u, MG_SPR_CTR=9u, MG_SPR_DSISR=18u,\n"
        " MG_SPR_DAR=19u, MG_SPR_SRR0=26u, MG_SPR_SRR1=27u,\n"
        " MG_SPR_EAR=282u, MG_SPR_GQR0=912u, MG_SPR_HID2=920u\n"
        "};\n"
        "static inline bool moderngekko_state_dirty(\n"
        "    const uint64_t* mask, uint32_t slot) {\n"
        "    return ((mask[slot / 64u] >> (slot % 64u)) & 1u) != 0u;\n"
        "}\n"
        "static inline uint32_t moderngekko_state_mask32(\n"
        "    const uint64_t* mask, uint32_t slot) {\n"
        "    uint32_t word = slot / 64u;\n"
        "    uint32_t shift = slot % 64u;\n"
        "    uint64_t bits = mask[word] >> shift;\n"
        "    if (shift > 32u) bits |= mask[word + 1u] << (64u - shift);\n"
        "    return (uint32_t)bits;\n"
        "}\n"
        "#if defined(_MSC_VER)\n"
        "#define DOLRECOMP_COLD __declspec(noinline)\n"
        "#else\n"
        "#define DOLRECOMP_COLD __attribute__((cold,noinline))\n"
        "#endif\n"
        "DOLRECOMP_COLD void moderngekko_commit_state(\n"
        "    const MGNativeState* state, const uint64_t* values,\n"
        "    const uint64_t* mask) {\n"
        "    void* context = state->context;\n"
        "    uint32_t gpr_mask = moderngekko_state_mask32(mask, MG_STATE_GPR0);\n"
        "    uint32_t ps0_mask = moderngekko_state_mask32(mask, MG_STATE_FPR0);\n"
        "    uint32_t ps1_mask = moderngekko_state_mask32(mask, MG_STATE_PS1_0);\n"
        "    bool registers_written = false;\n"
        "    if ((gpr_mask | ps0_mask | ps1_mask) != 0u &&\n"
        "        state->struct_size >= offsetof(MGNativeState, try_write_registers) +\n"
        "                                  sizeof(state->try_write_registers) &&\n"
        "        state->try_write_registers) {\n"
        "        registers_written = state->try_write_registers(\n"
        "            state, values + MG_STATE_GPR0, values + MG_STATE_FPR0,\n"
        "            values + MG_STATE_PS1_0, gpr_mask, ps0_mask, ps1_mask) != 0u;\n"
        "    }\n"
        "    if (!registers_written) {\n"
        "        for (uint32_t reg = 0; reg < 32u; reg++) {\n"
        "            if (gpr_mask & (1u << reg))\n"
        "                state->write_gpr(context, reg, (uint32_t)values[MG_STATE_GPR0 + reg]);\n"
        "            if (ps0_mask & (1u << reg))\n"
        "                state->write_fpr(context, reg, 0u, values[MG_STATE_FPR0 + reg]);\n"
        "            if (ps1_mask & (1u << reg))\n"
        "                state->write_fpr(context, reg, 1u, values[MG_STATE_PS1_0 + reg]);\n"
        "        }\n"
        "    }\n"
        "    bool cr_dirty = moderngekko_state_dirty(mask, MG_STATE_CR);\n"
        "    for (uint32_t field = 0; field < 8u; field++)\n"
        "        cr_dirty |= moderngekko_state_dirty(mask, MG_STATE_CR0 + field);\n"
        "    if (cr_dirty) {\n"
        "        uint32_t cr = moderngekko_state_dirty(mask, MG_STATE_CR)\n"
        "                          ? (uint32_t)values[MG_STATE_CR]\n"
        "                          : state->read_cr(context);\n"
        "        for (uint32_t field = 0; field < 8u; field++) {\n"
        "            uint32_t slot = MG_STATE_CR0 + field;\n"
        "            if (!moderngekko_state_dirty(mask, slot)) continue;\n"
        "            uint32_t shift = 28u - 4u * field;\n"
        "            cr = (cr & ~(15u << shift)) |\n"
        "                 (((uint32_t)values[slot] & 15u) << shift);\n"
        "        }\n"
        "        state->write_cr(context, cr);\n"
        "    }\n"
        "    bool xer_dirty = moderngekko_state_dirty(mask, MG_STATE_XER);\n"
        "    xer_dirty |= moderngekko_state_dirty(mask, MG_STATE_XER_CA);\n"
        "    xer_dirty |= moderngekko_state_dirty(mask, MG_STATE_XER_OV);\n"
        "    xer_dirty |= moderngekko_state_dirty(mask, MG_STATE_XER_SO);\n"
        "    if (xer_dirty) {\n"
        "        uint32_t xer = state->read_xer(context);\n"
        "        if (moderngekko_state_dirty(mask, MG_STATE_XER))\n"
        "            xer = (xer & 0xe0000000u) |\n"
        "                  ((uint32_t)values[MG_STATE_XER] & 0x1fffffffu);\n"
        "        const uint32_t slots[3] = {MG_STATE_XER_CA, MG_STATE_XER_OV, MG_STATE_XER_SO};\n"
        "        for (uint32_t bit = 0; bit < 3u; bit++) {\n"
        "            if (!moderngekko_state_dirty(mask, slots[bit])) continue;\n"
        "            uint32_t shift = 29u + bit;\n"
        "            xer = (xer & ~(1u << shift)) |\n"
        "                  (((uint32_t)values[slots[bit]] & 1u) << shift);\n"
        "        }\n"
        "        state->write_xer(context, xer);\n"
        "    }\n",
        out);
    fputs(
        "    const uint32_t spr_slots[8] = {MG_STATE_LR, MG_STATE_CTR, MG_STATE_SRR0,\n"
        "        MG_STATE_SRR1, MG_STATE_DAR, MG_STATE_DSISR, MG_STATE_EAR, MG_STATE_HID2};\n"
        "    const uint32_t spr_ids[8] = {MG_SPR_LR, MG_SPR_CTR, MG_SPR_SRR0,\n"
        "        MG_SPR_SRR1, MG_SPR_DAR, MG_SPR_DSISR, MG_SPR_EAR, MG_SPR_HID2};\n"
        "    for (uint32_t index = 0; index < 8u; index++)\n"
        "        if (moderngekko_state_dirty(mask, spr_slots[index]))\n"
        "            state->write_spr(context, spr_ids[index],\n"
        "                             (uint32_t)values[spr_slots[index]]);\n"
        "    for (uint32_t index = 0; index < 16u; index++)\n"
        "        if (moderngekko_state_dirty(mask, MG_STATE_SR0 + index))\n"
        "            state->write_sr(context, index, (uint32_t)values[MG_STATE_SR0 + index]);\n"
        "    for (uint32_t index = 0; index < 8u; index++)\n"
        "        if (moderngekko_state_dirty(mask, MG_STATE_GQR0 + index))\n"
        "            state->write_spr(context, MG_SPR_GQR0 + index,\n"
        "                             (uint32_t)values[MG_STATE_GQR0 + index]);\n"
        "    if (moderngekko_state_dirty(mask, MG_STATE_FPSCR))\n"
        "        state->write_fpscr(context, (uint32_t)values[MG_STATE_FPSCR]);\n"
        "    if (moderngekko_state_dirty(mask, MG_STATE_MSR))\n"
        "        state->write_msr(context, (uint32_t)values[MG_STATE_MSR]);\n"
        "    if (moderngekko_state_dirty(mask, MG_STATE_EXCEPTION))\n"
        "        state->write_exceptions(context, (uint32_t)values[MG_STATE_EXCEPTION]);\n"
        "    if (moderngekko_state_dirty(mask, MG_STATE_RESERVE_ADDR))\n"
        "        state->write_reserve_address(context,\n"
        "                                     (uint32_t)values[MG_STATE_RESERVE_ADDR]);\n"
        "    if (moderngekko_state_dirty(mask, MG_STATE_RESERVE_VALID))\n"
        "        state->write_reserve_valid(context,\n"
        "                                   (uint32_t)values[MG_STATE_RESERVE_VALID]);\n"
        "}\n",
        out);
    fputs(
        "DOLRECOMP_COLD void moderngekko_reload_state(\n"
        "    const MGNativeState* state, uint64_t* values,\n"
        "    const uint64_t* mask) {\n"
        "    void* context = state->context;\n"
        "    uint32_t gpr_mask = moderngekko_state_mask32(mask, MG_STATE_GPR0);\n"
        "    uint32_t ps0_mask = moderngekko_state_mask32(mask, MG_STATE_FPR0);\n"
        "    uint32_t ps1_mask = moderngekko_state_mask32(mask, MG_STATE_PS1_0);\n"
        "    bool registers_read = false;\n"
        "    if ((gpr_mask | ps0_mask | ps1_mask) != 0u &&\n"
        "        state->struct_size >= offsetof(MGNativeState, try_read_registers) +\n"
        "                                  sizeof(state->try_read_registers) &&\n"
        "        state->try_read_registers) {\n"
        "        registers_read = state->try_read_registers(\n"
        "            state, values + MG_STATE_GPR0, values + MG_STATE_FPR0,\n"
        "            values + MG_STATE_PS1_0, gpr_mask, ps0_mask, ps1_mask) != 0u;\n"
        "    }\n"
        "    if (!registers_read) {\n"
        "        for (uint32_t reg = 0; reg < 32u; reg++) {\n"
        "            if (gpr_mask & (1u << reg))\n"
        "                values[MG_STATE_GPR0 + reg] = state->read_gpr(context, reg);\n"
        "            if (ps0_mask & (1u << reg))\n"
        "                values[MG_STATE_FPR0 + reg] = state->read_fpr(context, reg, 0u);\n"
        "            if (ps1_mask & (1u << reg))\n"
        "                values[MG_STATE_PS1_0 + reg] = state->read_fpr(context, reg, 1u);\n"
        "        }\n"
        "    }\n"
        "    bool cr_needed = moderngekko_state_dirty(mask, MG_STATE_CR);\n"
        "    for (uint32_t field = 0; field < 8u; field++)\n"
        "        cr_needed |= moderngekko_state_dirty(mask, MG_STATE_CR0 + field);\n"
        "    if (cr_needed) {\n"
        "        uint32_t cr = state->read_cr(context);\n"
        "        if (moderngekko_state_dirty(mask, MG_STATE_CR))\n"
        "            values[MG_STATE_CR] = cr;\n"
        "        for (uint32_t field = 0; field < 8u; field++)\n"
        "            if (moderngekko_state_dirty(mask, MG_STATE_CR0 + field))\n"
        "                values[MG_STATE_CR0 + field] = (cr >> (28u - 4u * field)) & 15u;\n"
        "    }\n"
        "    bool xer_needed = moderngekko_state_dirty(mask, MG_STATE_XER);\n"
        "    xer_needed |= moderngekko_state_dirty(mask, MG_STATE_XER_CA);\n"
        "    xer_needed |= moderngekko_state_dirty(mask, MG_STATE_XER_OV);\n"
        "    xer_needed |= moderngekko_state_dirty(mask, MG_STATE_XER_SO);\n"
        "    if (xer_needed) {\n"
        "        uint32_t xer = state->read_xer(context);\n"
        "        if (moderngekko_state_dirty(mask, MG_STATE_XER))\n"
        "            values[MG_STATE_XER] = xer;\n"
        "        const uint32_t slots[3] = {MG_STATE_XER_CA, MG_STATE_XER_OV, MG_STATE_XER_SO};\n"
        "        for (uint32_t bit = 0; bit < 3u; bit++)\n"
        "            if (moderngekko_state_dirty(mask, slots[bit]))\n"
        "                values[slots[bit]] = (xer >> (29u + bit)) & 1u;\n"
        "    }\n",
        out);
    fputs(
        "    const uint32_t spr_slots[8] = {MG_STATE_LR, MG_STATE_CTR, MG_STATE_SRR0,\n"
        "        MG_STATE_SRR1, MG_STATE_DAR, MG_STATE_DSISR, MG_STATE_EAR, MG_STATE_HID2};\n"
        "    const uint32_t spr_ids[8] = {MG_SPR_LR, MG_SPR_CTR, MG_SPR_SRR0,\n"
        "        MG_SPR_SRR1, MG_SPR_DAR, MG_SPR_DSISR, MG_SPR_EAR, MG_SPR_HID2};\n"
        "    for (uint32_t index = 0; index < 8u; index++)\n"
        "        if (moderngekko_state_dirty(mask, spr_slots[index]))\n"
        "            values[spr_slots[index]] = state->read_spr(context, spr_ids[index]);\n"
        "    for (uint32_t index = 0; index < 16u; index++)\n"
        "        if (moderngekko_state_dirty(mask, MG_STATE_SR0 + index))\n"
        "            values[MG_STATE_SR0 + index] = state->read_sr(context, index);\n"
        "    for (uint32_t index = 0; index < 8u; index++)\n"
        "        if (moderngekko_state_dirty(mask, MG_STATE_GQR0 + index))\n"
        "            values[MG_STATE_GQR0 + index] =\n"
        "                state->read_spr(context, MG_SPR_GQR0 + index);\n"
        "    if (moderngekko_state_dirty(mask, MG_STATE_FPSCR))\n"
        "        values[MG_STATE_FPSCR] = state->read_fpscr(context);\n"
        "    if (moderngekko_state_dirty(mask, MG_STATE_MSR))\n"
        "        values[MG_STATE_MSR] = state->read_msr(context);\n"
        "    if (moderngekko_state_dirty(mask, MG_STATE_EXCEPTION))\n"
        "        values[MG_STATE_EXCEPTION] = state->read_exceptions(context);\n"
        "    if (moderngekko_state_dirty(mask, MG_STATE_RESERVE_ADDR))\n"
        "        values[MG_STATE_RESERVE_ADDR] = state->read_reserve_address(context);\n"
        "    if (moderngekko_state_dirty(mask, MG_STATE_RESERVE_VALID))\n"
        "        values[MG_STATE_RESERVE_VALID] = state->read_reserve_valid(context) != 0u;\n"
        "}\n"
        "DOLRECOMP_COLD uint32_t moderngekko_try_write_msr(\n"
        "    const MGNativeRuntime* runtime, uint32_t old_msr, uint32_t new_msr,\n"
        "    uint64_t elapsed) {\n"
        "    const MGNativeServices* services = runtime->services;\n"
        "    if (!services || services->struct_size < sizeof(*services) ||\n"
        "        !services->try_write_msr) return 0u;\n"
        "    return services->try_write_msr(services->context, old_msr, new_msr, elapsed);\n"
        "}\n"
        "DOLRECOMP_COLD uint32_t moderngekko_read_memory(\n"
        "    const MGNativeRuntime* runtime, uint32_t pc, uint32_t address,\n"
        "    uint32_t size, uint64_t elapsed, uint64_t* value,\n"
        "    uint32_t* remaining) {\n"
        "    const MGNativeServices* services = runtime->services;\n"
        "    MGNativeMemoryResult result = services->read_memory(\n"
        "        services->context, pc, address, size, elapsed);\n"
        "    *value = result.value;\n"
        "    *remaining = result.remaining_cycles;\n"
        "    return result.status;\n"
        "}\n"
        "DOLRECOMP_COLD uint32_t moderngekko_write_memory(\n"
        "    const MGNativeRuntime* runtime, uint32_t pc, uint32_t address,\n"
        "    uint64_t value, uint32_t size, uint64_t elapsed,\n"
        "    uint32_t* remaining) {\n"
        "    const MGNativeServices* services = runtime->services;\n"
        "    MGNativeMemoryResult result = services->write_memory(\n"
        "        services->context, pc, address, value, size, elapsed);\n"
        "    *remaining = result.remaining_cycles;\n"
        "    return result.status;\n"
        "}\n"
        "#undef DOLRECOMP_COLD\n",
        out);
}
